### ISSUE TITLE
Inference Pipeline?

### ISSUE THREAD

**Issue by norsedrunkensailor** [WillHua127/EnzymeFlow#2]
Hello!,

Love your work on EnzymeFlow, I was wondering whether there would be an opportunity to include a demo_inference.ipynb also? (naturally once the dependency issues have been solved) Like which files we need, etc so that people can begin design enzymes for experimental verification!

All the best, 
NDS

**Comment by WillHua127** [comment]
Yes, plan to release in Nov.

**Comment by WillHua127** [comment]
things should be fixed, let me know if you can run enzymeflow_demo.ipynb

**Comment by norsedrunkensailor** [comment]
Hello!

so I can load the model and software seems to be running fine! However, the file system implies I cannot run the Jupyter demo as for example 'generated/enzymeflow_demo/P07964_12616/P07964_12616/sample_0.pdb' is missing as well as looking for files in your directories: '/Users/willhua/Desktop/EnzymeFlow/data/processed_eval/protein/p07964/P07964.pkl'.

Perhaps there is a way to generate a demo file where all the information (input data) is in a single demo folder along with the Jupyter demo 

All the best, 
NDS

**Comment by WillHua127** [comment]
you may:
(d) You can also process evaluation data by running process_data.py. Remeber to change the configs, e.g., python process_data.py --rawdata_file_name eval-data_cutoff-0.1_unique-subs-enz_100.csv --metadata_file_name metadata_eval.csv.

Once run process_data.py for evaluation data, you may run jupyter notebook

**Comment by WillHua127** [comment]
Just remember to change the path in process_data.py
