### ISSUE TITLE
train_ddp.py FAILED

### ISSUE THREAD

**Issue by 123wnk** [WillHua127/EnzymeFlow#6]
resume training for checkpoint/enzymeflow_mini.ckpt
/data/wnk/EnzymeFlow-main/train_ddp.py:270: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.ckpt_path, map_location='cpu')
resume training for checkpoint/enzymeflow_mini.ckpt
/data/wnk/EnzymeFlow-main/train_ddp.py:270: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.ckpt_path, map_location='cpu')
resume training for checkpoint/enzymeflow_mini.ckpt
/data/wnk/EnzymeFlow-main/train_ddp.py:270: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.ckpt_path, map_location='cpu')
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/wnk/EnzymeFlow-main/train_ddp.py", line 466, in <module>
[rank0]:     main(args)
[rank0]:   File "/data/wnk/EnzymeFlow-main/train_ddp.py", line 278, in main
[rank0]:     model.load_state_dict(new_state_dict, strict=True)
[rank0]:   File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for ProteinLigandNetwork:
[rank0]:        size mismatch for ec_embedding_layer.0.weight: copying a param with shape torch.Size([7, 32]) from checkpoint, the shape in current model is torch.Size([6, 32]).
[rank0]:        size mismatch for ec_pred.4.weight: copying a param with shape torch.Size([7, 256]) from checkpoint, the shape in current model is torch.Size([6, 256]).
[rank0]:        size mismatch for ec_pred.4.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([6]).
resume training for checkpoint/enzymeflow_mini.ckpt
/data/wnk/EnzymeFlow-main/train_ddp.py:270: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.ckpt_path, map_location='cpu')
W1027 17:13:42.781000 22694970513216 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 167624 closing signal SIGTERM
W1027 17:13:42.782000 22694970513216 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 167625 closing signal SIGTERM
W1027 17:13:42.782000 22694970513216 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 167626 closing signal SIGTERM
E1027 17:13:43.411000 22694970513216 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 167623) of binary: /home/wnk/anaconda3/envs/python3.11/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wnk/anaconda3/envs/python3.11/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================

**Comment by WillHua127** [comment]
Simply added args.flow_ec = True: https://github.com/WillHua127/EnzymeFlow/blob/ed68ac72592d85091369e4e761944905b7f0e13d/train_ddp.py#L419

Should work now.

**Comment by 123wnk** [comment]
Thanks very much！
