### ISSUE TITLE
Issue with Downloading uid_to_protein_msa.pkl 

### ISSUE THREAD

**Issue by jiangqiiii** [WillHua127/EnzymeFlow#8]
Hi WillHua！
Thank you for providing this resource. I encountered an issue trying to download the uid_to_protein_msa.pkl file from the link provided, but it seems inaccessible. Could you please check the link, or provide an alternative method to access this file?

Thank you for your help!

![微信图片_20241104201520](https://github.com/user-attachments/assets/3a250a13-8b84-4a3c-a786-edcae50e22be)

**Comment by WillHua127** [comment]
it relates to training data. we plan to release in May or June 2025.
