### ISSUE TITLE
load checkpoint error 

### ISSUE THREAD

**Issue by LiuKeFromChina** [WillHua127/EnzymeFlow#9]
Hi!

I met an error while loading checkpoint in enzymeflow_demo.ipynb 
![image](https://github.com/user-attachments/assets/811aea07-9db6-4ed0-89d2-23a3fd8bb3ec)

![image](https://github.com/user-attachments/assets/db5d8eb4-6231-46eb-aa2b-2ee7ca15fe3a)

**Comment by WillHua127** [comment]
check your config: guide_by_condition. is it set to True?

**Comment by WillHua127** [comment]
i believe you changed some configs. so the model did not initialize the ProteinLigandNetwork

**Comment by LiuKeFromChina** [comment]
Thanks, I checked and I didn't change anything in config.py 。
The error message indicates that some keys are missing in the state_dict, while others are unexpected. I checked the corresponding missing and extra keys, and I found that they are quite similar but not identical. For example, in the missing keys, there is a key called guide_ligand_mpnn.mpnn.atom_convs.0.lin.weight, while in the extra keys, there are two similar ones called guide_ligand_mpnn.mpnn.atom_convs.0.lin_src.weight and guide_ligand_mpnn.mpnn.atom_convs.0.lin_dst.weight. I think this could be the reason for the issue―what do you think? Are these referring to the same layer?
[cid:42f549d4-e11a-4e10-aecb-16b9ab4dbda3]


________________________________
发件人: WillHua127 ***@***.***>
发送时间: 2024年11月6日 23:11
收件人: WillHua127/EnzymeFlow ***@***.***>
抄送: LiuKeFromChina ***@***.***>; Author ***@***.***>
主题: Re: [WillHua127/EnzymeFlow] load checkpoint error (Issue #9)


i believe you changed some configs. so the model did not initialize the ProteinLigandNetwork

―

**Comment by LiuKeFromChina** [comment]
![屏幕截图 2024-11-07 085201](https://github.com/user-attachments/assets/badffe11-9b0c-44fb-8b25-f04201b8913c)

**Comment by WillHua127** [comment]
if your torch geometric dependency == 2.4.0?

**Comment by LiuKeFromChina** [comment]
You're absolutely right; my torch geometric version was 2.6.1. After changing it to 2.4.0, the error disappeared. Thank you so much!

________________________________
发件人: WillHua127 ***@***.***>
发送时间: 2024年11月7日 8:58
收件人: WillHua127/EnzymeFlow ***@***.***>
抄送: LiuKeFromChina ***@***.***>; Author ***@***.***>
主题: Re: [WillHua127/EnzymeFlow] load checkpoint error (Issue #9)


is your torch geometric dependency == 2.4.0?

―

**Comment by LiuKeFromChina** [comment]
You're absolutely right; my torch geometric version was 2.6.1. After changing it to 2.4.0, the error disappeared. Thank you so much!

________________________________
发件人: WillHua127 ***@***.***>
发送时间: 2024年11月7日 8:58
收件人: WillHua127/EnzymeFlow ***@***.***>
抄送: LiuKeFromChina ***@***.***>; Author ***@***.***>
主题: Re: [WillHua127/EnzymeFlow] load checkpoint error (Issue #9)


is your torch geometric dependency == 2.4.0?

―
